### ISSUE TITLE
DEPRECATION: loadCSS & registerSettings

### ISSUE THREAD

**Issue by Bilibox** [cloudrac3r/pc-cadence-pluginUpdater#2]
These two are deprecated as of now. 
https://github.com/powercord-org/powercord/wiki/May-2020-Migration-Guide

**Comment by cloudrac3r** [comment]
I no longer maintain this plugin since I left powercord in late 2019 and got rid of my discord account in mid 2020. You'll have to fork it and update it if you want it to work in the future.
